- name: Install saorpg-roller application helm charts and manifests
  hosts: localhost
  vars_files:
  - "{{ [playbook_dir, 'vars/secrets.yaml'] | ansible.builtin.path_join }}"

  tasks:
  - name: Create namespace
    kubernetes.core.k8s:
      apply: true
      src: "{{ [playbook_dir, 'files/namespace.yaml'] | ansible.builtin.path_join }}"

  # Temporary for testing
  - name: Install httpbin
    kubernetes.core.k8s:
      apply: true
      # Requires ansible kubernetes collections >= 2.4.0 (latest is fine)
      src: "https://raw.githubusercontent.com/apache/apisix-ingress-controller/refs/heads/v2.0.0/examples/httpbin/deployment.yaml"
      namespace: saorpg-roller

  - name: Install saorpg-roller helm chart
    kubernetes.core.helm:
      name: saorpg-roller
      chart_ref: "{{ [playbook_dir, '..', 'helm'] | ansible.builtin.path_join }}"
      create_namespace: true
      release_namespace: saorpg-roller
      values:
        storageClass: local-path
        secretManager:
          accessKeyId: "{{ aws.sm.access_key_id }}"
          secretAccessKey: "{{ aws.sm.secret_access_key }}"
    no_log: true
