---
- name: Install miscellaneous stuff
  hosts: localhost

  tasks:
  - name: Install helm-diff plugin
    kubernetes.core.helm_plugin:
      plugin_path: https://github.com/databus23/helm-diff

- name: Install helm chart repositories
  hosts: localhost

  tasks:
  - name: Add cloudnative-pg repository
    kubernetes.core.helm_repository:
      name: cnpg
      repo_url: "https://cloudnative-pg.github.io/charts"

  - name: Add cert-manager repository
    kubernetes.core.helm_repository:
      name: jetstack
      repo_url: "https://charts.jetstack.io"

  - name: Add external-secrets repository
    kubernetes.core.helm_repository:
      name: external-secrets
      repo_url: "https://charts.external-secrets.io"

  - name: Add traefik repository
    kubernetes.core.helm_repository:
      name: traefik
      repo_url: "https://traefik.github.io/charts"

  - name: Add external-dns repository
    kubernetes.core.helm_repository:
      name: external-dns
      repo_url: "https://kubernetes-sigs.github.io/external-dns/"

- name: Install helm charts and manifests
  hosts: localhost
  vars_files:
  - "vars/secrets.yaml"

  tasks:
  - name: Install cloudnative-pg operator
    kubernetes.core.helm:
      name: cnpg
      chart_ref: cnpg/cloudnative-pg
      create_namespace: true
      release_namespace: cnpg-system

  - name: Install cert-manager controller
    kubernetes.core.helm:
      name: cert-manager
      chart_ref: jetstack/cert-manager
      create_namespace: true
      release_namespace: cert-manager
      values:
        crds:
          enabled: true

  - name: Install plugin-barman-cloud to backup cloudnative-pg cluster
    kubernetes.core.k8s:
      apply: true
      # Requires ansible kubernetes collections >= 2.4.0 (latest is fine)
      src: "https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.5.0/manifest.yaml"

  - name: Install external-secrets operator
    kubernetes.core.helm:
      name: external-secrets
      chart_ref: external-secrets/external-secrets
      create_namespace: true
      release_namespace: external-secrets

  - name: Install experimental Gateway API CRDs
    kubernetes.core.k8s:
      apply: true
      src: "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/experimental-install.yaml"

  - name: Install traefik proxy
    kubernetes.core.helm:
      name: traefik
      chart_ref: traefik/traefik
      create_namespace: true
      release_namespace: traefik
      values_files:
      - "{{ [playbook_dir, 'files/traefik_values.yaml'] | ansible.builtin.path_join }}"

  - name: Install external-dns controller
    kubernetes.core.helm:
      name: external-dns
      chart_ref: external-dns/external-dns
      create_namespace: true
      # Use the same namespace because otherwise cannot access secrets
      # Which would then require us to duplicate the installs
      release_namespace: saorpg-roller
      values:
        provider:
          name: cloudflare
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-dns-creds
              key: CF_API_TOKEN
        sources:
        - gateway-tlsroute
        - gateway-httproute

  # - name: Wait for prerequisites to be finished initializing
  #   ansible.builtin.wait_for:
  #     timeout: 120

- name: Install saorpg-roller application
  ansible.builtin.import_playbook: deploy_app.yaml
