---
- name: Uninstall helm charts and manifests
  hosts: localhost

  tasks:
  - name: Uninstall saorpg-roller helm charts
    kubernetes.core.helm:
      name: saorpg-roller
      release_namespace: saorpg-roller
      state: absent

  - name: Uninstall external-dns controller
    kubernetes.core.helm:
      name: external-dns
      release_namespace: saorpg-roller
      state: absent

  - name: Uninstall apisix ingress controller
    kubernetes.core.helm:
      name: apisix
      release_namespace: apisix-ingress
      state: absent

  - name: Uninstall external-secrets opererator
    kubernetes.core.helm:
      name: external-secrets
      release_namespace: external-secrets
      state: absent

  - name: Uninstall plugin-barman-cloud manifest
    kubernetes.core.k8s:
      # Requires ansible kubernetes collections >= 2.4.0 (latest is fine)
      src: "https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.5.0/manifest.yaml"
      state: absent

  - name: Uninstall cert-manager controller
    kubernetes.core.helm:
      name: cert-manager
      release_namespace: cert-manager
      state: absent

  - name: Uninstall cloudnative-pg operator
    kubernetes.core.helm:
      name: cnpg
      release_namespace: cnpg-system
      state: absent

- name: Delete namespaces
  hosts: localhost

  tasks:
  - name: Delete namespaces
    kubernetes.core.k8s:
      name: "{{ item }}"
      api_version: v1
      kind: Namespace
      state: absent
    loop:
    - saorpg-roller
    - external-dns
    - apisix-ingress
    - external-secrets
    - cert-manager
    - cnpg-system
