name: devcontainer

services:
  dev-machine:
    build:
      dockerfile: ./.devcontainer/development.Containerfile
    command: sleep infinity
    volumes:
    - .:/workspace:rw,z,cached
    network_mode: host
    environment:
      API_SERVER_CONTAINER: dev-machine
      SQITCH_USER_CONFIG: /run/secrets/sqitch_config
      DATABASE_SERVICE_NAME: db
    secrets:
    - sqitch_config

  db:
    build:
      dockerfile: ./.devcontainer/database.Containerfile
    restart: unless-stopped
    ports:
    - 6543:5432
    security_opt:
    - no-new-privileges:true
    volumes:
    - postgres-data:/var/lib/postgresql/data:rw,z
    - ./.devcontainer/database/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro,Z
    - ./database/configuration/postgresql.conf:/etc/postgresql/postgresql.conf:ro,Z
    - ./database:/usr/local/src/postgresql:ro,Z
    - ./database/src/shell:/docker-entrypoint-initdb.d:ro,Z
    command:
    - -c
    - config_file=/etc/postgresql/postgresql.conf
    - -c
    - hba_file=/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data:
    external: true

secrets:
  sqitch_config:
    file: ./.devcontainer/database/sqitch.conf
