name: devcontainer

services:
  dev-machine:
    build:
      dockerfile: ./.devcontainer/development.Containerfile
    security_opt:
    - no-new-privileges:true
    command: sleep infinity
    volumes:
    - .:/workspace:rw,z,cached
    networks:
      - external
      - internal
    environment:
      API_SERVER_CONTAINER: dev-machine
      SQITCH_USER_CONFIG: /run/secrets/sqitch_config
      DATABASE_SERVICE_NAME: db
    secrets:
    - sqitch_config

  db:
    build:
      dockerfile: ./.devcontainer/database.Containerfile
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    volumes:
    - postgres-data:/var/lib/postgresql/data:rw,z
    - ./.devcontainer/database/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro,Z
    - ./database/configuration/postgresql.conf:/etc/postgresql/postgresql.conf:ro,Z
    - ./database:/usr/local/src/postgresql:ro,Z
    - ./database/src/shell:/docker-entrypoint-initdb.d:ro,Z
    networks:
    - internal
    command:
    - -c
    - config_file=/etc/postgresql/postgresql.conf
    - -c
    - hba_file=/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  proxy:
    image: nginxinc/nginx-unprivileged
    security_opt:
    - no-new-privileges:true
    environment:
      API_SERVER_CONTAINER: dev-machine
      FRONTEND_SERVER_CONTAINER: dev-machine
    ports:
      - 8080:8080
    volumes:
    - ./infrastructure/src/nginx/templates:/etc/nginx/templates:ro,Z
    networks:
      - external
      - internal

volumes:
  postgres-data:
    external: true

networks:
  # Internal network is added to secure database while using trust authentication
  external:
  internal:
    internal: true

secrets:
  sqitch_config:
    file: ./.devcontainer/database/sqitch.conf
