apiVersion: v1
kind: Secret
metadata:
  name: awssm-secret
stringData:
  access-key: {{ .Values.secretManager.accessKeyId }}
  secret-access-key: {{ .Values.secretManager.secretAccessKey }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: awssm-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-1
      role: arn:aws:iam::894865518514:role/saorpg-roller-aws-iam-role-sm
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
