services:
  dev-machine:
    build:
      context: .
      dockerfile: development.Containerfile
    security_opt:
    - no-new-privileges:true
    command: sleep infinity
    volumes:
    - ..:/workspace:rw,z,cached
    networks:
      - external
      - internal
    environment:
      SQITCH_USER_CONFIG: /run/secrets/sqitch_config
    secrets:
    - sqitch_config

  db:
    build:
      context: .
      dockerfile: database.Containerfile
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    volumes:
    - postgres-data:/var/lib/postgresql/data:rw,z
    - ./database/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro,Z
    - ../database/configuration/postgresql.conf:/etc/postgresql/postgresql.conf:ro,Z
    - ../database:/usr/local/src/postgresql:ro,Z
    - ../database/src/shell:/docker-entrypoint-initdb.d:ro,Z
    ports:
    - 5432
    networks:
    - internal
    command:
    - -c
    - config_file=/etc/postgresql/postgresql.conf
    - -c
    - hba_file=/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_admin_password
    secrets:
    - postgres_admin_password

  proxy:
    image: nginxinc/nginx-unprivileged
    security_opt:
    - no-new-privileges:true
    environment:
      API_SERVER_CONTAINER: dev-machine
      FRONTEND_SERVER_CONTAINER: dev-machine
    ports:
      - 8080:8080
    volumes:
    - ../infrastructure/src/nginx/templates:/etc/nginx/templates:ro,Z
    networks:
      - external
      - internal

volumes:
  postgres-data:
    external: true

networks:
  # Internal network is added to secure database while using trust authentication
  external:
  internal:
    internal: true

secrets:
  sqitch_config:
    file: database/sqitch.conf
  postgres_admin_password:
    file: database/POSTGRES_PASSWORD
