apiVersion: k3d.io/v1alpha5
kind: Simple
ports:
  - port: 80:80
    nodeFilters:
    - loadbalancer
  - port: 443:443
    nodeFilters:
    - loadbalancer
  - port: 8000:8000
    nodeFilters:
    - loadbalancer
  - port: 5432:5432
    nodeFilters:
    - loadbalancer
options:
  k3s:
    extraArgs:
    - arg: "--disable=traefik"
      nodeFilters:
      - server:0
