environments:
  default:
    values:
    - environment/common/values.yaml
    - environment/development/values.yaml
    - environment/development/secrets.yaml
  production:
    values:
    - environment/common/values.yaml
    - environment/production/values.yaml
---
repositories:
- name: jetstack
  url: https://charts.jetstack.io
- name: traefik
  url: https://traefik.github.io/charts
- name: external-dns
  url: https://kubernetes-sigs.github.io/external-dns

releases:
- name: cert-manager
  namespace: "{{ .Values.namespace.certManager }}"
  chart: jetstack/cert-manager
  values:
  - values/cert-manager.yaml
- name: traefik
  namespace: "{{ .Values.namespace.traefik }}"
  chart: traefik/traefik
  values:
  - values/traefik.yaml.gotmpl
  hooks:
  - events: [presync]
    showlogs: true
    command: kubectl
    args:
    # Note: These links may need to change depending on 
    - apply
    - --server-side
    - -f
    - "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/experimental-install.yaml"
  - events: [postuninstall]
    showlogs: true
    command: kubectl
    args:
    - delete
    - -f
    - "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/experimental-install.yaml"
  needs:
  - "{{ .Values.namespace.certManager }}/cert-manager"
- name: external-dns
  namespace: "{{ .Values.namespace.saorpgRoller }}"
  chart: external-dns/external-dns
  condition: externalDns.enabled
  values:
  - values/external-dns.yaml
- name: saorpg-roller
  namespace: "{{ .Values.namespace.saorpgRoller }}"
  chart: ../helm/saorpg-roller
  values:
  - values/saorpg-roller.yaml
  needs:
  - "{{ .Values.namespace.traefik }}/traefik"
  installed: false
