environments:
  default:
    values:
    - environment/common/values.yaml
    - environment/development/values.yaml
    - environment/development/secrets.yaml
  production:
    values:
    - environment/common/values.yaml
    - environment/production/values.yaml
---
repositories:
- name: traefik
  url: https://traefik.github.io/charts
- name: external-dns
  url: https://kubernetes-sigs.github.io/external-dns

releases:
- name: cert-manager
  namespace: "{{ .Values.namespace.certManager }}"
  chart: oci://quay.io/jetstack/charts/cert-manager
  version: v1.19.2
  values:
  - values/cert-manager.yaml
- name: origin-ca-issuer
  namespace: "{{ .Values.namespace.certManager }}"
  chart: oci://ghcr.io/cloudflare/origin-ca-issuer-charts/origin-ca-issuer 
  version: 0.5.10
  condition: traefik.certManager.originCAIssuer.enabled
  hooks:
  - events: [presync]
    showlogs: true
    command: kubectl
    args:
    # Note: These links may need to change depending on 
    - apply
    - --server-side
    - -f
    - "https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/{{ .Values.origin-ca-issuer.crds.version }}/deploy/crds/cert-manager.k8s.cloudflare.com_originissuers.yaml"
  - events: [postuninstall]
    showlogs: true
    command: kubectl
    args:
    - delete
    - -f
    - "https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/{{ .Values.origin-ca-issuer.crds.version }}/deploy/crds/cert-manager.k8s.cloudflare.com_originissuers.yaml"
  needs:
  - "{{ .Values.namespace.certManager }}/cert-manager"
- name: traefik
  namespace: "{{ .Values.namespace.traefik }}"
  chart: traefik/traefik
  values:
  - values/traefik.yaml.gotmpl
  hooks:
  - events: [presync]
    showlogs: true
    command: kubectl
    args:
    # Note: These links may need to change depending on 
    - apply
    - --server-side
    - -f
    - "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/experimental-install.yaml"
  - events: [postuninstall]
    showlogs: true
    command: kubectl
    args:
    - delete
    - -f
    - "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/experimental-install.yaml"
  needs:
  - "{{ .Values.namespace.certManager }}/origin-ca-issuer"
- name: external-dns
  namespace: "{{ .Values.namespace.saorpgRoller }}"
  chart: external-dns/external-dns
  condition: externalDns.enabled
  values:
  - values/external-dns.yaml
- name: saorpg-roller
  namespace: "{{ .Values.namespace.saorpgRoller }}"
  chart: ../helm/saorpg-roller
  values:
  - values/saorpg-roller.yaml.gotmpl
  needs:
  - "{{ .Values.namespace.traefik }}/traefik"
- name: dev-database
  namespace: "{{ .Values.namespace.developmentDatabase }}"
  chart: ../helm/dev-database
  condition: developmentDatabase.enabled
  values:
  - values/dev-database.yaml.gotmpl
