apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "saorpg-roller.fullname" . }}
spec:
  instances: {{ .Values.instanceCount }}

  storage:
    size: {{ .Values.storageSize }}
    storageClass: {{ .Values.storageClass }}

  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.postgresqlConf }}
  postgresql:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if .Values.backup.enabled }}
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: aws-backup-store
  {{- end }}
